Add files via upload
LEAGUE-Level7/deforestation-game pull request #17
Opened 2020-08-25 01:37 UTC by eliyahubowers

the questions

2020-08-25 02:22 UTC, KevinWh0 commented
I think that these questions need some work:
burn down 1/2 of the forest - Why would you burn down 1/2 of the forest? You want to make paper, so why would burning it down help you in any way??
hire protestors - I doubt that the protesters would want to be hired by a company that they are protesting against
licesnce removal of forest - I don't understand this (does it mean, get a license to chop the forest, or sell a license?)
a hospital needs space for ading the sick - I don't understand this one

The other questions make sense, it's just these ones that don't so you might want to review those.

2020-08-25 02:22 UTC, ChaoticLeah requested changes
I think that these questions need some work:
burn down 1/2 of the forest - Why would you burn down 1/2 of the forest? You want to make paper, so why would burning it down help you in any way??
hire protestors - I doubt that the protesters would want to be hired by a company that they are protesting against
licesnce removal of forest - I don't understand this (does it mean, get a license to chop the forest, or sell a license?)
a hospital needs space for ading the sick - I don't understand this one

The other questions make sense, it's just these ones that don't so you might want to review those.

2020-08-25 02:22 UTC, KevinWh0 commented
I think that these questions need some work:
burn down 1/2 of the forest - Why would you burn down 1/2 of the forest? You want to make paper, so why would burning it down help you in any way??
hire protestors - I doubt that the protesters would want to be hired by a company that they are protesting against
licesnce removal of forest - I don't understand this (does it mean, get a license to chop the forest, or sell a license?)
a hospital needs space for ading the sick - I don't understand this one

The other questions make sense, it's just these ones that don't so you might want to review those.

2020-08-25 02:29 UTC, RyanGPalmer commented on questions.txt
> +{ your forest is burning, give money for forest fighting; none : it burns ; $10,000 : decreases somewhaT ; $100,000 : decreases significantly}
I really like this one! Makes you choose between two resources which is a good dynamic for the player

2020-08-25 02:50 UTC, ChaoticLeah reviewed
Might want to describe what Coverup means. Also does license removal of forest mean cut it down or what? Also by increase the quality of living for natives, do you mean the people who live in the forest(Indians, etc)?

2020-08-25 02:51 UTC, eanewman commented
I think the questions will be constantly evolving since this is really just the first cut, but this is some good material to work with :). This is a good opportunity to collaborate not only with Cindy, who is working on the coding side of the question task, but also with Ryland, who is working on the core logic. It's good to start thinking about how the questions and the data you collect from each question can be used to directly feed into the core algorithm for computing the current score. Again, this is definitely going to be an iterative process! Just something to think about.

2020-09-01 02:17 UTC, eliyahubowers commented
Cover up: just means to make it seem like your dealings are not as shady as they actually are.
license removal of forest: give other people a license to cut down trees (for a price).
They are the natives of the forest (the people living there).

2020-09-08 02:00 UTC, KevinWh0 requested changes
for question 1, "Turn wood into goods", if you already have the wood, why would it change people's opinion on you? (I think it needs some rewording) Also if you did something bad in the past and you don't pay to cover up your bad deeds you might want to make it so there is a chance that they find out and hate you a bit more.

2020-11-10 02:41 UTC, closed without merging